name: Release

on:
  release:
    types: [created]

jobs:
  tag:
      name: Tag
      runs-on: ubuntu-latest
      timeout-minutes: 5
      if: github.ref == 'refs/heads/main' # Skip PRs
      needs: test
      outputs:
        created-tag: ${{ steps.create-tag.outputs.tag }}
      steps:
        - name: Check out
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
        - name: Tag
          id: create-tag
          uses: salsify/action-detect-and-tag-new-version@v2

    publish:
      name: Publish
      runs-on: ubuntu-latest
      timeout-minutes: 5
      needs: tag
      if: needs.tag.outputs.created-tag != null
      steps:
        - name: Check out
          uses: actions/checkout@v3
        - name: Set up Node
          uses: actions/setup-node@v3
          with:
            node-version: 16
            registry-url: https://registry.npmjs.org
        - name: Build
          run: npm ci
        - name: Publish
          run: npm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
