name: Release

on:
  release:
    types: [created]

jobs:
  publish-packages:
    name: Publish packages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Extract tag version
        id: extract-tag-version
        run: |
          TAG="${GITHUB_REF:10}"
          TAG_VERSION="${TAG//v/}"
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Build
        run: npm ci

      - name: Publish
        run: |
          npm version ${{ env.TAG_VERSION }} && \
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

